apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ${CI_PROJECT_NAME}
  namespace: ${KUBE_NAMESPACE}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ${CI_PROJECT_NAME}
  minReplicas: ${K8S_MIN_REPLICAS}
  maxReplicas: ${K8S_MAX_REPLICAS}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: ${K8S_HPA_CPU_AU}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: ${K8S_HPA_MEM_AU}
