export enum WindowsEvents {
  CART_HEADER = 'CART_HEADER',
  CART_DATA = 'CART_DATA',
  GET_CART_ID = 'GET_CART_ID',
  GET_SHOPPING_CART = 'GET_SHOPPING_CART',
  CART_ID = 'CART_ID',
  ANALYTICS = 'ANALYTICS',
  TOGGLE_CART_ASIDE = 'TOGGLE_CART_ASIDE',
  UPDATE_SHIPPING_CART = 'UPDATE_SHIPPING_CART',
  OPEN_LOGIN_MODAL = 'OPEN_LOGIN_MODAL',
  DISPATCH_GET_CART_ID = 'DISPATCH_GET_CART_ID',
  DISPATCH_GET_CART = 'DISPATCH_GET_CART',
}
