export enum AUTH_EVENTS {
  DISPATCH_LOGOUT = 'DISPATCH_LOGOUT',
  DISPATCH_SIGNIN = 'DISPATCH_SIGNIN',
  DISPATCH_SIGNUP = 'DISPATCH_SIGNUP',
  DISPATCH_ACCESS_KEY_VALIDATION = 'DISPATCH_ACCESS_KEY_VALIDATION',
  DISPATCH_SET_PASSWORD = 'DISPATCH_SET_PASSWORD',
  GET_SIGNUP_SUCCESS = 'GET_SIGNUP_SUCCESS',
  GET_SIGNUP_ERROR = 'GET_SIGNUP_ERROR',
}
