name: Deploy to k8s
run-name: deploy-to-k8s
on: [push, workflow_dispatch]
jobs:
  k8s:
    uses: Cencosud-Cencommerce/actions/.github/workflows/deploy-to-k8s.yml@main
    secrets: inherit
    with:
      dry-run: 'false'
      environment: ${{(github.ref_name == 'master' && 'production') || (github.ref_name == 'uat' && 'uat') || 'staging'}}
